apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: k8s-program
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/datum"
