apiVersion: v1
kind: Service
metadata:
  name: songs-app
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-app-pod
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8080
      nodePort: 30001
