apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pods-content
  namespace: k8s
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
