apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: k8s
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:17.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
              subPath: songs
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d/            
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: pods-content
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-config
