apiVersion: v1
kind: Service
metadata:
  name: resources-app
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-app-pod
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8080
      nodePort: 30002
