apiVersion: v1
kind: Service
metadata:
  name: songs-app
  namespace: k8s
spec:
  type: NodePort
  selector:
    app: songs-app-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
      nodePort: 30002
