apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-app
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: songs-app-pod
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: songs-app-pod
        owner: tubaserj
    spec:
      containers:
        - name: songs-container
          image: registry.digitalocean.com/stradarium-registry/songs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_NAME
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: SONGS_MS_NAME
            - name: SONGS_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: SONGS_MS_PORT
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: DB_URL
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: DB_PORT
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: EUREKA_CLIENT_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: EUREKA_CLIENT_ENABLED
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 90
