apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-app
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: songs-app-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: songs-app-pod
        owner: tubaserj
    spec:
      containers:
        - name: songs-container
          image: registry.digitalocean.com/stradarium-registry/songs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_NAME
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: SONGS_DB_URL
              value: "postgres-service"
            - name: SONGS_DB_PORT
              value: "5432"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
