apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-resources
  namespace: k8s-program
spec:
  serviceName: postgres-resources
  replicas: 1
  selector:
    matchLabels:
      app: postgres-resources
  template:
    metadata:
      labels:
        app: postgres-resources
    spec:
      containers:
        - name: postgres-resources
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: task-pv-claim
