apiVersion: v1
kind: Service
metadata:
  name: postgres-songs
  namespace: k8s-program
  labels:
    app: postgres-songs
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres-songs
