apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-app
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: resources-app-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: resources-app-pod
        owner: tubaserj
    spec:
      containers:
        - name: resources-container
          image: registry.digitalocean.com/stradarium-registry/resources-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_MS_NAME
              value: "resources-ms"
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: SONGS_MS_URL
              value: "songs-app"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: RESOURCES_DB_URL
              value: "postgres-service"
            - name: RESOURCES_DB_PORT
              value: "5432"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 90
