apiVersion: v1
kind: Service
metadata:
  name: postgres-resources
  namespace: k8s-program
  labels:
    app: postgres-resources
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres-resources
