# Default values for songs-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: helm

songsApp:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 2
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: registry.digitalocean.com/stradarium-registry/songs-app
    # This sets the pull policy for images.
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  label: songs-app-pod

resourcesApp:
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 2
  test: 3
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: registry.digitalocean.com/stradarium-registry/resources-app
    # This sets the pull policy for images.
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  label: resources-app-pod
