apiVersion: v1
kind: Service
metadata:
  name: resources-app
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: resources-app-pod
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30003
