apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: {{ .Values.namespace }}
data:
  init.sql: |
    create table resources (id serial not null, blob bytea, primary key (id));
    create sequence songs_seq start with 1 increment by 50;
    create table songs (id integer not null, resource_id integer not null unique, album varchar(255), artist varchar(255), length varchar(255), name varchar(255), year varchar(255), primary key (id));
